"use client";

import { motion } from "framer-motion";
import { ArrowRight, Check, Download, FileDown, FileText, Sparkles } from "lucide-react";
import { SectionLabel, cn } from "./primitives";
import { BarChart } from "./charts";

const CLEANING_ROWS = [
  { before: "revenue=\"\"", after: "revenue=2,450.00", ok: true },
  { before: "Date: \"03/12/25\"", after: "2025-03-12", ok: true },
  { before: "  total   ", after: "total", ok: true },
  { before: "region=??", after: "region=West", ok: true },
];

function ReportPageMock() {
  return (
    <div className="relative">
      <div aria-hidden className="absolute -inset-6 rounded-[2rem] bg-gradient-to-br from-violet-600/25 to-cyan-500/20 blur-2xl" />

      <motion.div
        initial={{ opacity: 0, rotate: -3, y: 24 }}
        whileInView={{ opacity: 1, rotate: -1.5, y: 0 }}
        viewport={{ once: true, margin: "-80px" }}
        transition={{ duration: 0.9, ease: [0.22, 1, 0.36, 1] }}
        className="relative mx-auto w-full max-w-md rounded-xl bg-[#f4f5fa] p-6 text-slate-900 shadow-card-3d"
        whileHover={{ rotate: 0, y: -6 }}
      >
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-gradient-to-br from-violet-500 to-cyan-500 text-white">
              <Sparkles className="h-3.5 w-3.5" />
            </span>
            <p className="text-xs font-bold uppercase tracking-wider text-slate-500">AutoData Report</p>
          </div>
          <span className="rounded-full bg-emerald-100 px-2.5 py-1 text-[9px] font-bold uppercase tracking-wider text-emerald-700">
            PII redacted
          </span>
        </div>

        <h3 className="mt-4 font-display text-lg font-bold tracking-tight text-slate-900">Sales Analysis — Q4</h3>
        <div className="mt-1 flex items-center gap-2 text-[10px] text-slate-500">
          <span>Generated by AutoData</span>
          <span>·</span>
          <span>sales_q4.csv</span>
        </div>

        <div className="mt-4 grid grid-cols-3 gap-2.5">
          {[
            { l: "Revenue", v: "$1.24M" },
            { l: "Orders", v: "8,431" },
            { l: "Quality", v: "92/100" },
          ].map((k) => (
            <div key={k.l} className="rounded-lg bg-white px-3 py-2.5 shadow-sm ring-1 ring-slate-100">
              <p className="text-[9px] font-medium uppercase tracking-wider text-slate-400">{k.l}</p>
              <p className="font-display text-sm font-bold text-slate-900">{k.v}</p>
            </div>
          ))}
        </div>

        <div className="mt-4 rounded-lg bg-white px-3 py-3 shadow-sm ring-1 ring-slate-100">
          <p className="mb-1 text-[9px] font-semibold uppercase tracking-wider text-slate-400">Revenue by region</p>
          <BarChart values={[48, 72, 58, 90, 66]} width={280} height={70} from="#7c3aed" to="#0891b2" />
        </div>

        <div className="mt-3 space-y-1.5">
          <div className="h-1.5 w-full rounded-full bg-slate-200" />
          <div className="h-1.5 w-4/5 rounded-full bg-slate-200" />
          <div className="h-1.5 w-2/3 rounded-full bg-slate-100" />
        </div>

        <div className="mt-4 flex items-center justify-between border-t border-slate-200 pt-3">
          <p className="text-[9px] text-slate-400">Exportable as PDF · HTML · Markdown</p>
          <span className="flex h-6 w-6 items-center justify-center rounded-lg bg-gradient-to-br from-violet-500 to-cyan-500 text-white">
            <Download className="h-3 w-3" />
          </span>
        </div>
      </motion.div>

      <motion.div
        initial={{ opacity: 0, y: 16 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
        transition={{ delay: 0.7, duration: 0.6 }}
        className="absolute -right-3 bottom-10 flex rotate-2 items-center gap-2 rounded-xl border border-white/10 bg-night-800/95 px-3.5 py-2.5 shadow-card-3d backdrop-blur-xl"
      >
        <span className="flex h-6 w-6 items-center justify-center rounded-full bg-emerald-500/20 text-emerald-400">
          <Check className="h-3.5 w-3.5" />
        </span>
        <div>
          <p className="text-[10px] font-semibold text-white">Report ready</p>
          <p className="text-[9px] text-slate-400">report_sales_q4.pdf · 2.1 MB</p>
        </div>
      </motion.div>
    </div>
  );
}

export function Report() {
  return (
    <section id="report" className="relative mx-auto max-w-7xl scroll-mt-24 px-5 py-28 sm:px-8">
      <div className="grid items-center gap-14 lg:grid-cols-2 lg:gap-16">
        <div>
          <SectionLabel>Reports &amp; export</SectionLabel>
          <h2 className="mt-6 font-display text-4xl font-bold leading-[1.08] tracking-tight text-white sm:text-5xl">
            Clean the mess. Then make it <span className="text-gradient-animated">look effortless.</span>
          </h2>
          <p className="mt-5 text-lg leading-relaxed text-slate-400">
            A guided cleaning studio fixes your file while you watch, then compiles everything into a report your
            stakeholders will actually read.
          </p>

          <div className="mt-8 space-y-2">
            {CLEANING_ROWS.map((row, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 14 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: 0.1 + i * 0.09 }}
                className="flex items-center gap-3 rounded-xl border border-white/[0.07] bg-white/[0.03] px-4 py-3"
              >
                <span className="w-32 truncate rounded-lg bg-rose-500/10 px-2.5 py-1 font-mono text-[10px] text-rose-300 line-through decoration-rose-500/50">
                  {row.before}
                </span>
                <ArrowRight className="h-3.5 w-3.5 shrink-0 text-slate-500" />
                <span className="flex-1 truncate rounded-lg bg-emerald-500/10 px-2.5 py-1 font-mono text-[10px] text-emerald-300">
                  {row.after}
                </span>
                <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-emerald-500/20 text-emerald-400">
                  <Check className="h-3 w-3" />
                </span>
              </motion.div>
            ))}
          </div>

          <div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-4">
            {[
              { icon: FileDown, label: "CSV / XLSX" },
              { icon: FileText, label: "Markdown" },
              { icon: FileText, label: "HTML" },
              { icon: FileText, label: "PDF" },
            ].map((f, i) => (
              <motion.div
                key={f.label}
                initial={{ opacity: 0, scale: 0.92 }}
                whileInView={{ opacity: 1, scale: 1 }}
                viewport={{ once: true }}
                transition={{ delay: 0.15 + i * 0.07 }}
                className="flex flex-col items-center gap-1.5 rounded-2xl border border-white/[0.08] bg-white/[0.03] px-3 py-4 transition hover:border-white/20 hover:bg-white/[0.06]"
              >
                <f.icon className={cn("h-4 w-4", "text-slate-300")} />
                <span className="text-[10px] font-medium text-slate-400">{f.label}</span>
              </motion.div>
            ))}
          </div>
        </div>

        <ReportPageMock />
      </div>
    </section>
  );
}
