"""Professional report generation (Markdown + HTML + PDF).

Assembles the dataset overview, quality summary, key insights, correlations
and the *actual computed charts* into a single downloadable report. Nothing is
invented here - every number and every chart comes from the computed
analysis. Columns flagged as sensitive (PII) are summarised without their
values.
"""

from __future__ import annotations

import html
import re

from .ai.insights import dataset_overview_text
from .report_charts import pick_report_charts, svg_for_chart

CHART_SECTION = "6. Charts"


def _esc(v) -> str:
    if v is None:
        return "&ndash;"
    return html.escape(str(v))


def _visible_columns(engine) -> list[dict]:
    return [c for c in engine.columns if not c.get("sensitive")]


def _pick_charts(engine) -> list[dict]:
    return pick_report_charts(engine.chart_suggestions, max_charts=6)


def build_report_markdown(engine, dataset_name: str, insights: list[dict]) -> str:
    s = engine.summary
    columns = _visible_columns(engine)
    sensitive = [c["name"] for c in engine.columns if c.get("sensitive")]
    charts = _pick_charts(engine)
    lines = []
    lines.append(f"# AutoData Report — {dataset_name}")
    lines.append("")
    lines.append("## 1. Dataset Overview")
    lines.append("")
    lines.append(dataset_overview_text(engine))
    lines.append("")

    lines.append("## 2. Columns")
    lines.append("")
    lines.append("| Column | Type | Confidence | Missing | Distinct |")
    lines.append("| --- | --- | --- | --- | --- |")
    for c in columns:
        lines.append(
            f"| {c['name']} | {c['inferred_type']} | {c['confidence']} | "
            f"{c['null_pct']}% | {c['distinct_count']} |"
        )
    if sensitive:
        lines.append("")
        lines.append(f"_Note: {len(sensitive)} sensitive column(s) omitted: "
                     + ", ".join(f"`{c}`" for c in sensitive) + "._")
    lines.append("")

    lines.append("## 3. Data Quality")
    q = engine.quality["summary"]
    lines.append("")
    lines.append(
        f"Quality score: **{q['quality_score']}/100** ({q['total_issues']} issues: "
        f"{q['high']} high, {q['medium']} medium, {q['low']} low)."
    )
    lines.append("")
    for issue in engine.quality["issues"]:
        lines.append(f"- **[{issue['severity'].upper()}]** {issue['title']}: {issue['detail']}")
    lines.append("")

    lines.append("## 4. Key Insights")
    lines.append("")
    if not insights:
        lines.append("No significant patterns were detected in this dataset.")
    for i in insights:
        lines.append(f"### {i['title']}")
        lines.append("")
        lines.append(i["detail"])
        if i.get("numbers"):
            parts = ", ".join(f"{n['label']}: **{n['value']}**" for n in i["numbers"])
            lines.append(f"\n_{parts}_")
        lines.append("")

    lines.append("## 5. Correlations")
    lines.append("")
    if engine.strong_correlations:
        for p in engine.strong_correlations[:6]:
            lines.append(
                f"- {p['col_a']} & {p['col_b']}: **{p['correlation']:.2f}** ({p['strength']})"
            )
    else:
        lines.append("No strong correlations were found between numeric columns.")
    lines.append("")

    if charts:
        lines.append(f"## {CHART_SECTION}")
        lines.append("")
        lines.append("Visualisations generated from the analysis are included in the "
                     "HTML and PDF versions of this report.")
        lines.append("")

    lines.append("---")
    lines.append(f"*Generated by AutoData · {s['row_count']:,} rows × {s['column_count']} columns*")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Markdown -> HTML rendering (small, safe subset used for preview + download)
# ---------------------------------------------------------------------------

_INLINE_BOLD = re.compile(r"\*\*(.+?)\*\*")
_INLINE_CODE = re.compile(r"`([^`]+)`")
_INLINE_EM = re.compile(r"(?<!\*)\*([^*]+)\*(?!\*)")


def _inline(text: str) -> str:
    text = _esc(text)
    text = _INLINE_CODE.sub(r"<code>\1</code>", text)
    text = _INLINE_BOLD.sub(r"<strong>\1</strong>", text)
    text = _INLINE_EM.sub(r"<em>\1</em>", text)
    return text


def _is_table_sep(line: str) -> bool:
    cells = [c.strip() for c in line.strip().strip("|").split("|")]
    return bool(cells) and all(set(c) <= set("-: ") and c for c in cells)


def markdown_to_html(markdown_text: str) -> str:
    """Render a small Markdown subset to standalone, self-contained HTML."""
    out: list[str] = []
    lines = markdown_text.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]

        # Tables (header row + separator + body rows)
        if line.startswith("|") and i + 1 < len(lines) and _is_table_sep(lines[i + 1]):
            header = [c.strip() for c in line.strip().strip("|").split("|")]
            i += 2
            rows = []
            while i < len(lines) and lines[i].startswith("|"):
                cells = [c.strip() for c in lines[i].strip().strip("|").split("|")]
                rows.append(cells)
                i += 1
            head = "".join(f"<th>{_inline(c)}</th>" for c in header)
            body = "".join(
                "<tr>" + "".join(f"<td>{_inline(c)}</td>" for c in row) + "</tr>"
                for row in rows
            )
            out.append(f"<table><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table>")
            continue

        # Unordered lists
        if line.startswith("- "):
            items = []
            while i < len(lines) and lines[i].startswith("- "):
                items.append(f"<li>{_inline(lines[i][2:])}</li>")
                i += 1
            out.append("<ul>" + "".join(items) + "</ul>")
            continue

        # Headings
        for marker, tag in (("### ", "h3"), ("## ", "h2"), ("# ", "h1")):
            if line.startswith(marker):
                out.append(f"<{tag}>{_inline(line[len(marker):])}</{tag}>")
                i += 1
                break
        else:
            # Blockquote
            if line.startswith("> "):
                out.append(f"<blockquote>{_inline(line[2:])}</blockquote>")
            elif line.startswith("---"):
                out.append("<hr>")
            elif line.strip().startswith("_"):
                out.append(f"<p><em>{_inline(line.strip('_').strip())}</em></p>")
            elif line.strip() == "":
                out.append("")
            else:
                out.append(f"<p>{_inline(line)}</p>")
            i += 1

    body = "\n".join(out)
    return _html_document("Analysis Report", body, charts_html="")


def _html_document(title: str, body: str, charts_html: str) -> str:
    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{_esc(title)}</title>
<style>
:root {{ color-scheme: light; }}
* {{ box-sizing: border-box; }}
body {{ font-family: -apple-system, 'Segoe UI', Roboto, sans-serif; max-width: 900px; margin: 32px auto; padding: 0 24px; color: #1f2937; line-height: 1.65; }}
h1 {{ font-size: 28px; letter-spacing: -0.02em; border-bottom: 3px solid #7c3aed; padding-bottom: 10px; }}
h2 {{ margin-top: 36px; font-size: 20px; letter-spacing: -0.01em; color: #111827; }}
h3 {{ margin-top: 22px; font-size: 16px; }}
h2::before {{ content: ''; display: inline-block; width: 10px; height: 10px; margin-right: 8px; border-radius: 3px; background: linear-gradient(135deg, #7c3aed, #06b6d4); }}
table {{ border-collapse: collapse; width: 100%; margin: 14px 0; font-size: 13.5px; }}
th, td {{ border: 1px solid #e5e7eb; padding: 7px 11px; text-align: left; }}
thead th {{ background: #f3f0ff; font-weight: 600; color: #4c1d95; }}
tbody tr:nth-child(even) {{ background: #fafafa; }}
code {{ background: #f3f4f6; border: 1px solid #e5e7eb; border-radius: 5px; padding: 1px 5px; font-size: 0.9em; }}
ul {{ padding-left: 22px; }}
li {{ margin: 5px 0; }}
blockquote {{ border-left: 3px solid #a78bfa; margin: 14px 0; padding: 4px 16px; color: #4b5563; background: #faf7ff; }}
hr {{ border: 0; border-top: 1px solid #e5e7eb; margin: 34px 0; }}
figure {{ margin: 20px 0; padding: 18px; border: 1px solid #ede9fe; border-radius: 14px; background: #fcfbff; }}
figcaption {{ margin-top: 10px; font-size: 12px; color: #6b7280; text-align: center; }}
.grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(320px, 1fr)); gap: 8px; }}
.gauge-row {{ display: flex; align-items: center; gap: 18px; margin: 10px 0; }}
footer {{ margin-top: 40px; padding-top: 14px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 12px; }}
@media print {{ body {{ max-width: 100%; margin: 0; }} h2 {{ page-break-after: avoid; }} figure {{ break-inside: avoid; }} }}
</style></head>
<body>
{body}
{charts_html}
<footer>Generated by AutoData — automated analysis of the uploaded dataset.</footer>
</body></html>"""


def _quality_gauge(score: int) -> str:
    r = 40
    circ = 2 * 3.14159 * r
    frac = max(0, min(100, score)) / 100
    color = "#10b981" if score >= 80 else "#f59e0b" if score >= 60 else "#f43f5e"
    return (
        f'<svg viewBox="0 0 100 100" width="86" height="86" role="img" '
        f'aria-label="Quality score {score} out of 100">'
        f'<circle cx="50" cy="50" r="{r}" fill="none" stroke="#eef2ff" stroke-width="10"/>'
        f'<circle cx="50" cy="50" r="{r}" fill="none" stroke="{color}" stroke-width="10" '
        f'stroke-linecap="round" stroke-dasharray="{circ:.2f}" stroke-dashoffset="{circ * (1 - frac):.2f}" '
        f'transform="rotate(-90 50 50)"/>'
        f'<text x="50" y="55" text-anchor="middle" font-size="24" font-weight="700" fill="#111827">'
        f'{score}</text>'
        f'<text x="50" y="70" text-anchor="middle" font-size="8" fill="#6b7280">QUALITY</text>'
        f'</svg>'
    )


def build_report_html(engine, dataset_name: str, insights: list[dict]) -> str:
    """Build a self-contained HTML report with the computed charts embedded."""
    s = engine.summary
    q = engine.quality["summary"]
    columns = _visible_columns(engine)
    sensitive = [c["name"] for c in engine.columns if c.get("sensitive")]
    charts = _pick_charts(engine)

    sections = [
        "<h1>AutoData Report</h1>",
        f"<p class='muted'>{_esc(dataset_name)} · "
        f"{s['row_count']:,} rows × {s['column_count']} columns</p>",
    ]

    # 1. Overview
    sections.append("<h2>1. Dataset Overview</h2>")
    sections.append(f"<p>{_inline(dataset_overview_text(engine))}</p>")

    # 2. Columns
    sections.append("<h2>2. Columns</h2>")
    head = "".join(f"<th>{_esc(c)}</th>" for c in ["Column", "Type", "Confidence", "Missing", "Distinct"])
    body = "".join(
        "<tr>" + "".join(
            f"<td>{_esc(c['name'])}</td><td>{_esc(c['inferred_type'])}</td>"
            f"<td>{_esc(c['confidence'])}</td><td>{_esc(c['null_pct'])}%</td>"
            f"<td>{_esc(c['distinct_count'])}</td>"
        ) + "</tr>"
        for c in columns
    )
    sections.append(f"<table><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table>")
    if sensitive:
        sections.append(
            f"<blockquote><em>{len(sensitive)} sensitive column(s) omitted: "
            + ", ".join(f"<code>{_esc(c)}</code>" for c in sensitive)
            + ".</em></blockquote>"
        )

    # 3. Quality with gauge
    sections.append("<h2>3. Data Quality</h2>")
    sections.append(
        "<div class='gauge-row'>" + _quality_gauge(q["quality_score"]) +
        f"<p>{q['total_issues']} issue(s) detected: "
        f"<strong>{q['high']}</strong> high, <strong>{q['medium']}</strong> medium, "
        f"<strong>{q['low']}</strong> low.</p></div>"
    )
    issues = "".join(
        f"<li><strong>[{_esc(i['severity'].upper())}]</strong> {_esc(i['title'])} — {_esc(i['detail'])}</li>"
        for i in engine.quality["issues"]
    )
    if issues:
        sections.append(f"<ul>{issues}</ul>")

    # 4. Insights
    sections.append("<h2>4. Key Insights</h2>")
    if not insights:
        sections.append("<p>No significant patterns were detected in this dataset.</p>")
    for ins in insights:
        sections.append(f"<h3>{_esc(ins['title'])}</h3>")
        sections.append(f"<p>{_inline(ins['detail'])}</p>")
        if ins.get("numbers"):
            parts = ", ".join(
                f"{_esc(n['label'])}: <strong>{_esc(n['value'])}</strong>" for n in ins["numbers"]
            )
            sections.append(f"<p><em>{parts}</em></p>")

    # 5. Correlations
    sections.append("<h2>5. Correlations</h2>")
    if engine.strong_correlations:
        corr = "".join(
            f"<li>{_esc(p['col_a'])} &amp; {_esc(p['col_b'])}: "
            f"<strong>{p['correlation']:.2f}</strong> ({_esc(p['strength'])})</li>"
            for p in engine.strong_correlations[:6]
        )
        sections.append(f"<ul>{corr}</ul>")
    else:
        sections.append("<p>No strong correlations were found between numeric columns.</p>")

    # 6. Charts
    charts_html = ""
    if charts:
        charts_html = '<h2 id="charts">6. Charts</h2><div class="grid">'
        for chart in charts:
            svg = svg_for_chart(chart)
            if svg:
                charts_html += (
                    f"<figure>{svg}<figcaption>{_esc(chart.get('title', ''))}</figcaption></figure>"
                )
        charts_html += "</div>"

    return _html_document(f"AutoData Report — {dataset_name}", "\n".join(sections), charts_html)


# ---------------------------------------------------------------------------
# PDF report
# ---------------------------------------------------------------------------


def build_report_pdf(engine, dataset_name: str, insights: list[dict]) -> bytes:
    """Build a real, shareable PDF report (reportlab) with embedded charts."""
    from io import BytesIO

    from reportlab.lib import colors
    from reportlab.lib.enums import TA_LEFT
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import (
        KeepTogether,
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )

    from .report_pdf_charts import QualityBarFlowable, flowable_for_chart

    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(
        name="Tight", parent=styles["Normal"], spaceAfter=6, leading=14,
    ))
    styles.add(ParagraphStyle(
        name="H2Local", parent=styles["Heading2"], textColor=colors.HexColor("#4f46e5"),
        spaceBefore=14, spaceAfter=6,
    ))
    styles.add(ParagraphStyle(
        name="Muted", parent=styles["Normal"], textColor=colors.HexColor("#6b7280"),
        fontSize=9, spaceAfter=4,
    ))

    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=letter,
        leftMargin=0.85 * inch, rightMargin=0.85 * inch,
        topMargin=0.85 * inch, bottomMargin=0.85 * inch,
    )
    story = []
    story.append(Paragraph(f"AutoData Report — {_html(dataset_name)}", styles["Title"]))
    story.append(Paragraph("Automated data analysis", styles["Muted"]))
    story.append(Spacer(1, 10))

    story.append(Paragraph("1. Dataset Overview", styles["H2Local"]))
    story.append(Paragraph(_html(dataset_overview_text(engine)), styles["Tight"]))

    story.append(Paragraph("2. Columns", styles["H2Local"]))
    columns = _visible_columns(engine)
    sensitive = [c["name"] for c in engine.columns if c.get("sensitive")]
    col_data = [["Column", "Type", "Missing", "Distinct"]]
    for c in columns:
        col_data.append([_html(c["name"]), c["inferred_type"], f"{c['null_pct']}%", str(c["distinct_count"])])
    col_table = Table(col_data, colWidths=[2.4 * inch, 1.4 * inch, 1.0 * inch, 1.0 * inch], repeatRows=1)
    col_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#eef2ff")),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#e5e7eb")),
        ("FONTSIZE", (0, 0), (-1, -1), 8.5),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(col_table)
    if sensitive:
        story.append(Paragraph(
            f"<i>Sensitive columns omitted from this report: {_html(', '.join(sensitive))}.</i>",
            styles["Muted"],
        ))
    story.append(Spacer(1, 8))

    story.append(Paragraph("3. Data Quality", styles["H2Local"]))
    q = engine.quality["summary"]
    story.append(QualityBarFlowable(q["quality_score"], width=6.8 * inch, height=30))
    story.append(Paragraph(
        f"Quality score: <b>{q['quality_score']}/100</b> "
        f"({q['total_issues']} issues: {q['high']} high, {q['medium']} medium, {q['low']} low).",
        styles["Tight"],
    ))
    for issue in engine.quality["issues"][:12]:
        story.append(Paragraph(f"• <b>[{issue['severity'].upper()}]</b> {_html(issue['title'])} — {_html(issue['detail'])}", styles["Tight"]))

    story.append(Paragraph("4. Key Insights", styles["H2Local"]))
    if not insights:
        story.append(Paragraph("No significant patterns were detected in this dataset.", styles["Tight"]))
    for i in insights:
        story.append(KeepTogether([
            Paragraph(f"<b>{_html(i['title'])}</b>", styles["Tight"]),
            Paragraph(_html(i["detail"]), styles["Tight"]),
        ]))
        if i.get("numbers"):
            parts = ", ".join(f"{_html(n['label'])}: <b>{_html(n['value'])}</b>" for n in i["numbers"])
            story.append(Paragraph(parts, styles["Muted"]))

    story.append(Paragraph("5. Correlations", styles["H2Local"]))
    if engine.strong_correlations:
        for p in engine.strong_correlations[:6]:
            story.append(Paragraph(
                f"• {_html(p['col_a'])} & {_html(p['col_b'])}: <b>{p['correlation']:.2f}</b> ({p['strength']})",
                styles["Tight"],
            ))
    else:
        story.append(Paragraph("No strong correlations were found between numeric columns.", styles["Tight"]))

    charts = _pick_charts(engine)
    if charts:
        story.append(Paragraph("6. Charts", styles["H2Local"]))
        for chart in charts:
            flow = flowable_for_chart(chart, width=6.6 * inch, height=2.1 * inch)
            if flow is not None:
                story.append(KeepTogether([flow, Spacer(1, 10)]))

    story.append(Spacer(1, 16))
    story.append(Paragraph(
        f"Generated by AutoData · {engine.summary['row_count']:,} rows × {engine.summary['column_count']} columns",
        styles["Muted"],
    ))
    doc.build(story)
    return buf.getvalue()


def _html(text: str) -> str:
    return html.escape(str(text))
