"""Professional report generation (Markdown + HTML).

Assembles the dataset overview, quality summary, key insights and supporting
charts into a single downloadable report. All numbers come from the computed
analysis - nothing is invented here.
"""

from __future__ import annotations

import html

from .ai.insights import dataset_overview_text
from .data_engine import analysis


def _esc(v) -> str:
    if v is None:
        return "&ndash;"
    return html.escape(str(v))


def build_report_markdown(engine, dataset_name: str, insights: list[dict]) -> str:
    s = engine.summary
    lines = []
    lines.append(f"# AutoData Report — {dataset_name}")
    lines.append("")
    lines.append("## 1. Dataset Overview")
    lines.append("")
    lines.append(dataset_overview_text(engine))
    lines.append("")

    lines.append("## 2. Columns")
    lines.append("")
    lines.append("| Column | Type | Confidence | Missing | Distinct |")
    lines.append("| --- | --- | --- | --- | --- |")
    for c in engine.columns:
        lines.append(
            f"| {c['name']} | {c['inferred_type']} | {c['confidence']} | "
            f"{c['null_pct']}% | {c['distinct_count']} |"
        )
    lines.append("")

    lines.append("## 3. Data Quality")
    q = engine.quality["summary"]
    lines.append("")
    lines.append(
        f"Quality score: **{q['quality_score']}/100** ({q['total_issues']} issues: "
        f"{q['high']} high, {q['medium']} medium, {q['low']} low)."
    )
    lines.append("")
    for issue in engine.quality["issues"]:
        lines.append(f"- **[{issue['severity'].upper()}]** {issue['title']}: {issue['detail']}")
    lines.append("")

    lines.append("## 4. Key Insights")
    lines.append("")
    if not insights:
        lines.append("No significant patterns were detected in this dataset.")
    for i in insights:
        lines.append(f"### {i['title']}")
        lines.append("")
        lines.append(i["detail"])
        if i.get("numbers"):
            parts = ", ".join(f"{n['label']}: **{n['value']}**" for n in i["numbers"])
            lines.append(f"\n_{parts}_")
        lines.append("")

    lines.append("## 5. Correlations")
    lines.append("")
    if engine.strong_correlations:
        for p in engine.strong_correlations[:6]:
            lines.append(
                f"- {p['col_a']} & {p['col_b']}: **{p['correlation']:.2f}** ({p['strength']})"
            )
    else:
        lines.append("No strong correlations were found between numeric columns.")
    lines.append("")

    lines.append("---")
    lines.append(f"*Generated by AutoData · {s['row_count']:,} rows × {s['column_count']} columns*")
    return "\n".join(lines)


def markdown_to_html(markdown_text: str) -> str:
    """Very small Markdown subset renderer for the preview pane."""
    out = []
    for raw in markdown_text.splitlines():
        line = raw
        if line.startswith("### "):
            out.append(f"<h3>{_esc(line[4:])}</h3>")
        elif line.startswith("## "):
            out.append(f"<h2>{_esc(line[3:])}</h2>")
        elif line.startswith("# "):
            out.append(f"<h1>{_esc(line[2:])}</h1>")
        elif line.startswith("- "):
            out.append(f"<li>{_esc(line[2:])}</li>")
        elif line.startswith("| ") and "| ---" not in line:
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            out.append("<tr>" + "".join(f"<td>{_esc(c)}</td>" for c in cells) + "</tr>")
        elif line.startswith("---"):
            out.append("<hr>")
        elif line.strip().startswith("_"):
            out.append(f"<p><em>{_esc(line.strip('_').strip())}</em></p>")
        elif line.strip() == "":
            out.append("")
        else:
            out.append(f"<p>{_esc(line)}</p>")
    body = "\n".join(out)
    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8">
<title>Analysis Report</title>
<style>
body {{ font-family: -apple-system, Segoe UI, Roboto, sans-serif; max-width: 860px; margin: 32px auto; padding: 0 20px; color: #1f2937; line-height: 1.6; }}
h1 {{ border-bottom: 2px solid #4f46e5; padding-bottom: 8px; }}
table {{ border-collapse: collapse; width: 100%; }}
td {{ border: 1px solid #e5e7eb; padding: 6px 10px; font-size: 14px; }}
tr:first-child td {{ background: #f3f4f6; font-weight: 600; }}
li {{ margin: 4px 0; }}
</style></head>
<body>{body}</body></html>"""
